config/routes.rb
InvoicesApp::Application.routes.draw do
  devise_for :users
  resources :users
  resources :invoices do
  	member do
  		get 'sendreceipt'
  	end
  end
  resources :clients do
  	resources :invoices, only: [:index]
  end
  
  
  get '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
	

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	has_many :invoice_items, dependent: :destroy
	has_one :currency
	accepts_nested_attributes_for :invoice_items, :reject_if => lambda { |a| a[:item_title].blank? }, 
																 allow_destroy: true
	belongs_to :client
	belongs_to :user
	
	validates_presence_of :client_id
	validates_presence_of :project_title
	validates_presence_of :currency_id
	validates_presence_of :invoice_type
	
	before_save do |invoice| 
		client = Client.find_by_id(invoice.client_id)
		invoice.slug = "#{client.name.parameterize}-#{invoice.id}-#{invoice.project_title.parameterize}"
	end
	
	
	def to_param
		slug
	end
	
	def total_price(amount)
	    total = invoice_items.sum amount
	    unless self.discount.blank?
	    	discount = total * self.discount / 100
		    total -= discount
		else
			total
		end
	end
	

	
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :edit]

  # GET /invoices
  # GET /invoices.json
  def index
  	 @clients = Client.all
  	 if signed_in? 
  	 	if params[:client_id].nil?
 			 # url /invoices
 		 	 @invoices = @user.invoices
  	 	else
  	 		 # url /clients/:id/invoices
  	 		 @client = Client.find_by_id(params[:client_id])
	 		 @invoices = @client.invoices
 	 		 @single_client = true
  			 if !correct_user?
  			 	flash[:error] = "Not allowed!"
  			 	redirect_to root_path
  			 end
  	 	end
  	 else
  	 	if params[:client_id].nil?
	  	 	flash[:error] = "Not allowed"
  		 	redirect_to root_path
  		 else
  		 	@client = Client.find_by_id(params[:client_id])
  		 	@invoices = @client.invoices
  		 end
  	 end
  	
	 
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  	@user = User.find(@invoice.user_id)
	@client = Client.find_by_id(@invoice.client_id)
	@currency = Currency.find_by_id(@invoice.currency_id)
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.invoice_items.build
	@clients = @user.clients
	@currencies = Currency.all
	@clients_array = @clients.map { |client| [client.name, client.id] }
	@currencies_array = @currencies.map { |currency| [currency.title, currency.id] }
	@selected_client = params[:client_id]
	
  end

  # GET /invoices/1/edit
  def edit
  	@currencies = Currency.all
  	@clients = @user.clients
  	@invoice_items = Invoice.find_by_slug(params[:id]).invoice_items
  	@clients_array = @clients.map { |client| [client.name, client.id] }
  	@currencies_array = @currencies.map { |currency| [currency.title, currency.id] }
  	@selected_client = @invoice.client_id
  end

  # POST /invoices
  # POST /invoices.json
  def create
   @invoice = Invoice.create(invoice_params)
   @clients = Client.all
   @currencies = Currency.all
   @clients_array = @clients.map { |client| [client.name, client.id] }
   @currencies_array = @currencies.map { |currency| [currency.title, currency.id] }

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end
  
  def sendreceipt
  	@invoice = Invoice.find_by_slug(params[:id])
  	InvoiceMailer.send_receipt(@invoice).deliver
  	redirect_to invoice_path(@invoice)
  	flash[:notice] = "Email has been sent!"
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find_by_slug(params[:id])
    end
    
    def set_user
    	@user = current_user
    end
    
    def invoice_params
    	params.require(:invoice).permit(:project_title, 
    									:client_id, :notes, :slug, :user_id, :invoice_type, 
    									:currency_id, :paid, :discount, 
    									invoice_items_attributes: [:id, :invoice_id, :_destroy, :item_title, :item_desc, :item_amount] )
    end
    

end

app/helpers/invoices_helper.rb
module InvoicesHelper
	
	def isEstimate?
		@invoice.invoice_type == "Estimate"
	end

end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class=" col-md-12 field-invoice-title"><%= f.text_field :project_title, autofocus: true, placeholder: "Project Title", class: "form-control" %></div>
  
  

  <div class="form-group col-md-4">
    <%= f.label :client_id %><br>
    <%= f.select :client_id, options_for_select(@clients_array, @selected_client), { include_blank: true }, { :class => 'form-control' } %>
  </div>
  
  <div class="form-group col-md-4">
    <%= f.label :currency_id %><br>
    <%= f.select :currency_id, options_for_select(@currencies_array, @invoice.currency_id), { :include_blank => true }, { :class => 'form-control' } %>
  </div>
  
  <div class="form-group col-xs-4">
  	<%= f.label :invoice_type %><br />
  	<div class="radio-inline">
  		<%= f.radio_button(:invoice_type, "Estimate") %>
  		<%= f.label(:invoice_type_estimate, "Estimate") %>
  	</div>
  	<div class="radio-inline">
  		<%= f.radio_button(:invoice_type, "Invoice") %>
	  	<%= f.label(:invoice_type_invoice, "Invoice") %>
	 </div>
  </div>
  
  <div class="form-group col-lg-12 field-invoice-items row">
	  	<%= f.fields_for :invoice_items do |builder| %>
		  	<%= render 'invoice_item_fields', f: builder %>
		<% end %>
   	<%= link_to_add_fields "Add Item", f, :invoice_items %>
  </div>
  <div class="form-group col-xs-10 field-notes">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control", placeholder: "Additional details for the client" %>
    <%= f.hidden_field :slug %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group col-xs-2 field-discount">
  	<%= f.label :discount %>
  	<%= f.text_field :discount, placeholder: "Amount in %", class: "form-control" %>
  </div>
  <div class="actions col-xs-12 field-submit invoice-controls">
    <%= f.submit class: "btn btn-primary btn-lg centered" %>
  </div>
<% end %>

app/views/invoices/_invoice_item_fields.html.erb
<fieldset class="invoice-item-row row col-lg-12">
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
				<%= f.text_field :item_title, class: "form-control field-item-title", placeholder: "Item Title" %>
				<%= f.text_area :item_desc, class: "form-control field-item-desc", placeholder: "Description (Optional)", rows: 2 %>
			</div>
			<div class="col-lg-3 col-md-3 col-sm-3 col-xs-10 invoice-item-amount">
				<%= f.text_field :item_amount, class: "form-control field-item-amount", placeholder: "Amount" %>
			</div>
			<div class="close-btn col-lg-1 col-md-1 col-sm-1 col-xs-2">
				<%= f.hidden_field :_destroy %>
				<%= link_to "×", "#", class: "remove_fields btn close" %>
			</div>
</fieldset>

app/views/invoices/_list_invoices.html.erb
<table class="table table-responsive list invoice-list">
  <thead>
    <tr>
      <th>Project title</th>
      <th>Client</th>
      <th>Type</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td class="list-project-title"><%= link_to invoice.project_title, invoice %></td>
        <% client_id = @clients.find_by_id(invoice.client_id) %>
        <% unless client_id.nil? %>
       		<td class="list-client-name"><%= link_to client_id.name, 
        						client_invoices_url(client_id) %></td>
        <% else %>
        	<td class="list-client-name">[Client Deleted]</td>
        <% end %>
        <td class="list-type"><%= invoice.invoice_type %></td>
        <td class="list-paid"><% if invoice.paid? %> Paid <% else %> Pending <% end %></td>
        <td><%= link_to '×', invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: "close" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/_paid_form.html.erb
<%= form_for(@invoice) do |f| %>
	<div class="paid-form">
		<% if @invoice.paid? %>
			<span class="paid">Paid</span>
			<%= link_to "Send Receipt", sendreceipt_invoice_path(@invoice), class: "btn btn-primary" %>
		<% else %>
				
				<% if isEstimate? %>
					<%= f.hidden_field :invoice_type, value: "Invoice" %>
					<%= f.submit "Convert to Invoice", class: "btn btn-large btn-primary" %>
				<% else %>
					<!-- Is Invoice -->
					<%= f.hidden_field :paid, value: true %>
					<%= f.submit "Mark as paid", class: "btn btn-large btn-primary" %>
				<% end %>
		<% end %>
	</div>
<% end %>

app/views/invoices/edit.html.erb
<div class="row">
	<%= render 'form' %>
</div>

<div class="row col-xs-12">
	<%= link_to 'Show', @invoice %> |
	<%= link_to 'Back to All Invoices', invoices_path %>
</div>

app/views/invoices/index.html.erb
<% provide(:title, "All Invoices") %>


<% if @single_client.nil? %>
	
<% else %>
	<%= link_to "All Invoices", invoices_path %> >
	<span><%= @client.name %>'s Invoices</span>
<% end %>

<%= render 'list_invoices' %>

<% if signed_in? %>

	<% if @single_client.nil? %>
		<%= link_to 'New Invoice', new_invoice_path, class: "btn new-invoice-btn" %>
	<% else %>
		<%= link_to 'New Invoice', new_invoice_path(client_id: @client.id), class: "btn new-invoice-btn" %>
	<% end %>

<% end %>

app/views/invoices/new.html.erb
<div class="row">
	<%= render 'form' %>
	
	<div class="row col-md-12">
	<%= link_to 'Back to all Invoices', invoices_path %>
	</div>
</div>

app/views/invoices/show.html.erb
<% provide(:title, @invoice.project_title) %>

<div class="invoice-header">
	<%=  image_tag "hc-promo.png", alt: "Hash Cookies Logo" %>
	<p class="inv-company-title"><%= @user.company %> <span class="inv-date"><%= @invoice.invoice_type %> #<%= @invoice.id %></span></p>
	
</div>

<div class="stripe"></div>

<div class="inv-client-info">
	<div class="inv-client">
		<span class="inv-client-name"><%= @client.name %></span><br />
		<span class="inv-client-address"><%= @client.address %></span><br />
		<%= link_to "View all invoices", client_invoices_path(@client) %>
	</div>
	<div class="inv-proj">
		<span class="inv-project-title"><%= @invoice.project_title %></span><br />
		<span class="caps"><%= l @invoice.created_at, :format => :long %></span>
	</div>
</div>

<div class="stripe"></div>
	
<div class="invoice-wrapper">	
	
	<div class="invoice-details">
		<table class="table">
			<thead>
			  <tr>
			    <th>Description</th>
			    <th class="pull-right">Amount (in <%= @currency.symbol %>)</th>
			   </tr>
			</thead>
			<tbody>
			 	<% for invoice_item in @invoice.invoice_items %>
				 	<tr>
				 		<td class=" col-md-8">
				 			<p class="caps bold item-title"><%= invoice_item.item_title %></p>
					 		<p class="item-desc"><%= invoice_item.item_desc %></p>
				 		</td>
				 		<td class="pull-right item-amount  col-md-4">
				 			<% if !invoice_item.item_amount.blank? %>
					 			<p class="item-amount pull-right"><%= number_with_delimiter(invoice_item.item_amount, delimiter: ',')   %></p>
					 		<% else %>
					 			-
					 		<% end %>
				 		</td>
			 		</tr>
			 	<% end %>
			 	<% unless @invoice.discount.nil? %>
			 		<tr class="row-discount">
			 			<td class="title">Discount</td> 
			 			<td class="pull-right"><%= @invoice.discount %>%</td>
			 		</tr>
			 	<% end %>
		 	</tbody>
		</table>
		
		<p class="item-total"><span>Total</span> <%= @currency.symbol %> <%= @invoice.total_price :item_amount %> </p>
		<div class="stripe"></div>
	</div>
</div> <!--end invoice wrapper-->

<div class="invoice-notes">
  <strong>Notes:</strong><br />
  <%= @invoice.notes %>
</div>

<div class="stripe"></div>

<div class="invoice-footer">
	<div class="inv-user row col-lg-5 col-sm-12">
		<div class="user-name "><%= @user.name %></div>
		<div class="user-title"><%= @user.company %></div>
	</div>
	<div class="row col-lg-7 col-sm-12">
		<ul class="inv-user-meta pull-right">
			<li><%= @user.email %></li>
			<li><%= number_to_phone(@user.phone, country_code: 91) %></li>
			<li><%= @user.company_url %></li>
		</ul>
	</div>
</div>

<% if authorised? %>
	<div class="invoice-controls">
		<%= render 'paid_form' %>
	</div>
	<div class="inv-nav row col-md-12">
			<%= link_to 'Edit Invoice', edit_invoice_path(@invoice) %> |
			<%= link_to 'Back to Invoices', invoices_path %>
		
	</div>
<% end %>