config/routes.rb
InvoicesApp::Application.routes.draw do
  devise_for :users
  resources :users
  resources :invoices do
  	member do
  		get 'sendreceipt'
  	end
  end
  resources :clients do
  	resources :invoices, only: [:index]
  end
  
  
  get '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
	

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :invoices
	belongs_to :user
	
	validates_presence_of :name
	validates_presence_of :email
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	 before_action :set_client, only: [:destroy]

	def index
		@clients = current_user.clients
	end
	
	def show
		@clients = current_user.clients
		render 'index'
	end
	
	def new
		@client = Client.new
	end
	
	def create
		@client = Client.new(client_params)
		@client.user_id = current_user.id
		if @client.save
			flash[:success] = "Client created."
			redirect_to @client
		else
			render 'new'
		end
	end
	
	def destroy
	  @client.destroy
	  respond_to do |format|
	    format.html { redirect_to clients_url }
	    format.json { head :no_content }
	  end
	end
	
	private
	  # Use callbacks to share common setup or constraints between actions.
	  def set_client
	    @client = Client.find(params[:id])
	  end
	
	def client_params
		params.require(:client).permit(:name, :address, :user_id, :email)
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
	
	<% if @client.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this invoice from being saved:</h2>
	
	      <ul>
	      <% @client.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  
	<div class=" col-md-12 field-client-name"><%= f.text_field :name, placeholder: "Client Name", class: "form-control" %></div>
	
	<div class="form-group">
		<%= f.label :email, "Email (Required)" %>
		<%= f.text_field :email, class: "form-control" %>
	</div>
	
	<div class="form-group">
		<%= f.label :address, "Client Address" %>
		<%= f.text_area :address, class: "form-control" %>
	</div>
	
	<div class="form-group">
		<%= f.submit "Register Client", class: "btn btn-large btn-primary" %>
	</div>

<% end %>

app/views/clients/index.html.erb
<ul class="list-unstyled clients-list"><% @clients.each do |client| %>
	<li class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
		<span><%= link_to "×", client, method: :delete, data: { confirm: "Are you sure?" }, class: "close" %></span>
		<div class="client-info-wrap">
			<h3 class="client-name"><%= link_to client.name, client_invoices_url(client) %></h3>
			<p class="client-address"><%= client.address %></p>
		</div>
	</li>
<% end %>
</ul>

<div class="actions col-xs-12 field-submit invoice-controls">
	<%= link_to "New Client", new_client_path, class: "btn btn-primary" %>
</div>

app/views/clients/new.html.erb
<div class="row">
		<%= render 'form' %>
</div>

<%= link_to 'All Clients', clients_path %>