config/routes.rb
InvoicesApp::Application.routes.draw do
  devise_for :users
  resources :users
  resources :invoices do
  	member do
  		get 'sendreceipt'
  	end
  end
  resources :clients do
  	resources :invoices, only: [:index]
  end
  
  
  get '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
	

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "#invoices", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    	<% if user_signed_in? %>
	      <li class="<%= 'active' if current_page?(clients_path) %>"><%= link_to "Clients",  clients_path %></li>
	      <li class="<%= 'active' if current_page?(invoices_path) %>"><%= link_to "Invoices", invoices_path %></li>
	      <li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
	        <ul class="dropdown-menu">
	          <li><%= link_to "Profile", current_user %></li>
	          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	          <li class="divider"></li>
	          <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
	        </ul>
	      </li>
	     <% else %>
	     	<li><%= link_to "Log in", new_user_session_path %></li>	
	     <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <% if Rails.env.development? %>
  	<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
  <% end %>
</head>
<body>
	
	<%= render 'layouts/header' %>
	
	<div class="container main"> 
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			
			<%= yield %>
	</div>
	
	<footer id="footer">
		<%= debug(params) if Rails.env.development? %>
		&copy; Hash Cookies
	</footer>
	
</body>
</html>

app/views/layouts/homepage_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <% if Rails.env.development? %>
  	<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
  <% end %>
</head>
<body class="homepage">
	
	<ul class="home-nav">
		<li><%= link_to "Log in", new_user_session_path %></li>
		<li><%= link_to "About", about_path %></li>
	</ul>

	
	<div class="container main"> 
			
			<%= yield %>
	</div>
	
	<div id="promo-footer"><a href="http://hashcooki.es/">by Hash Cookies</a></div>
	

</body>
</html>